services:
  redis:
    image: ${REDIS_IMAGE:-adregistry.fnal.gov/instrumentation/redis@sha256:365ee40e627b9faf0775c31c7d6eb9e88a2de201e981b28bd5206029375977b6}
    container_name: redis-pvxs-ioc-redis
    networks:
      - redis-pvxs-ioc
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 15

  ioc:
    image: ${REDIS_PVXS_IOC_IMAGE:-adregistry.fnal.gov/instrumentation/redis-pvxs-ioc:v0.6.1@sha256:73ef6e1ca9e8e6c344e2663f841186050629b49a3f1ebe3c3ffa1e73ce4bfad5}
    container_name: redis-pvxs-ioc-demo
    networks:
      - redis-pvxs-ioc
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ${REDIS_PVXS_IOC_CONFIG:-./demo/config.yaml}:/etc/redis-pvxs-ioc/config.yaml:ro

networks:
  redis-pvxs-ioc:
    driver: bridge
