services:
  legacy-ioc:
    image: ${LEGACY_IOC_IMAGE:-adregistry.fnal.gov/instrumentation/redis-pvxs-ioc-legacy-sidecar:v0.2.0}
    container_name: redis-pvxs-ioc-legacy
    profiles:
      - legacy
    networks:
      - redis-pvxs-ioc
    environment:
      LEGACY_IOC_STARTUP: /etc/legacy-ioc/st.cmd
      LEGACY_IOC_ENABLE_CA: ${LEGACY_IOC_ENABLE_CA:-NO}
    volumes:
      - ${LEGACY_IOC_STARTUP_HOST:-./legacy-sidecar/iocBoot/st.cmd}:/etc/legacy-ioc/st.cmd:ro
