services:
  channelfinder-sync:
    image: ${REDIS_PVXS_IOC_IMAGE:-adregistry.fnal.gov/instrumentation/redis-pvxs-ioc:v0.6.1@sha256:73ef6e1ca9e8e6c344e2663f841186050629b49a3f1ebe3c3ffa1e73ce4bfad5}
    container_name: redis-pvxs-ioc-channelfinder-sync
    profiles:
      - channelfinder
    networks:
      - redis-pvxs-ioc
    entrypoint: ["/opt/redis-pvxs-ioc/bin/redis-pvxs-channelfinder-sync"]
    command: ["--config", "/etc/redis-pvxs-ioc/config.yaml", "--dry-run"]
    environment:
      CHANNELFINDER_USERNAME: ${CHANNELFINDER_USERNAME:-}
      CHANNELFINDER_PASSWORD: ${CHANNELFINDER_PASSWORD:-}
    volumes:
      - ${REDIS_PVXS_IOC_CONFIG:-./demo/config.yaml}:/etc/redis-pvxs-ioc/config.yaml:ro
