# Preserve full SemVer for runtime identity while CMake uses its numeric core.
if(NOT REDIS_PVXS_IOC_VERSION MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(-([0-9A-Za-z.-]+))?(\\+([0-9A-Za-z.-]+))?$")
  message(FATAL_ERROR "VERSION must contain a complete semantic version")
endif()
set(REDIS_PVXS_IOC_VERSION_CORE "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${CMAKE_MATCH_3}")
set(_version_prerelease "${CMAKE_MATCH_5}")
set(_version_metadata "${CMAKE_MATCH_7}")
string(REPLACE "." ";" _version_numbers "${REDIS_PVXS_IOC_VERSION_CORE}")
foreach(_number IN LISTS _version_numbers)
  if(_number MATCHES "^0[0-9]+$")
    message(FATAL_ERROR "VERSION core numbers cannot have leading zeros")
  endif()
endforeach()
foreach(_part IN ITEMS "${_version_prerelease}" "${_version_metadata}")
  if(_part MATCHES "^\\.|\\.\\.|\\.$")
    message(FATAL_ERROR "VERSION identifiers cannot be empty")
  endif()
endforeach()
string(REPLACE "." ";" _version_identifiers "${_version_prerelease}")
foreach(_identifier IN LISTS _version_identifiers)
  if(_identifier MATCHES "^0[0-9]+$")
    message(FATAL_ERROR "VERSION numeric prerelease identifiers cannot have leading zeros")
  endif()
endforeach()
